### ISSUE TITLE
[Bug] [Code: ATWxYRE] Not working after removing a language

### ISSUE THREAD

**Issue by guidev** [FlineDev/ReMafoX#101]
## Steps to Reproduce:

I've removed a couple of localization language from project -> info -> localisations (see attachment)

After that, I cannot use Remafox as It errors out with:

A file was expected but did not exist at: /path/to/project/sv.lproj/Localizable.strings

<img width="604" alt="Screenshot 2023-04-29 at 02 49 03" src="https://user-images.githubusercontent.com/1105813/235273833-776ebc5e-ec25-40c2-81d4-42993f9932b0.png">

## Environment

ATWxYRE

<details>
<summary>Show environment details</summary>

- App Version: 1.5.0 (Build 613)
- System Version: 13.3.1 (Build 22E261)
- System CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
- Tier: Free

</details>

**Comment by Jeehut** [comment]
@guidev Thank you for reporting this issue. I'll take a look at it tomorrow and do my best to provide a fix as soon as possible.

**Comment by Jeehut** [comment]
I investigated and I think I found the issue, the Add Translation Window isn't automatically rescanning the Strings files on open to have up-to-date information about which files exist and which don't. I will fix that with a hotfix release `1.5.1` ASAP.

In the meantime, pressing the "Rescan Strings(dict) files" button in the Add Translation window should update the paths manually after removing some languages which should make this error disappear:
<img width="1052" alt="Bildschirmfoto 2023-04-29 um 12 45 46" src="https://user-images.githubusercontent.com/6942160/235298671-625c4725-c751-4fc6-b618-b48fda647d1d.png">

I hope this helps!

**Comment by Jeehut** [comment]
@guidev I just made a change that should fix this issue and I'm uploading a new build with the fix right away. This issue should be resolved in version `1.5.1` which should be up on the App Store very soon.

Thanks again for reporting this issue! 👍
