### ISSUE TITLE
[Bug] [Code: PBRxAF] Project can't be opened

### ISSUE THREAD

**Issue by holgerkrupp** [FlineDev/ReMafoX#105]
## Steps to Reproduce:

1. Opening ReMaFox and selecting my project on the right side of the window

## Expected Behavior:

Opening the project in ReMaFoX

## Current Behavior:

project can't be opened

## Environment

PBRxAF

<details>
<summary>Show environment details</summary>

- App Version: 1.6.0 (Build 648)
- System Version: 13.4.1 (Build 22F82)
- System CPU: Apple M1
- Tier: Pro

</details>

**Comment by Jeehut** [comment]
@holgerkrupp Thank you for reporting this. Can you please give me additional information? Like a screenshot of the error? Could it be that the project has been moved?

**Comment by holgerkrupp** [comment]
The project has been restored from a Time Machine backup. Unfortunately I didn't take a screenshot, I reintegrated RemafoX with the project and now it's working again.

**Comment by Jeehut** [comment]
Sounds like moved paths might be in play here. If double-pressing the `.remafox` file and giving permission to access to the folder fixes the issue (it seems to have), then all seems fine from my perspective. Please let me know if you have any more details to share. But from what it sounds, I don't think there's anything to do. Closing.

Thanks again for reporting! 👍
