### ISSUE TITLE
[Bug] "Update Strings files from Storyboard/XIB files" not working

### ISSUE THREAD

**Issue by lukemmtt** [FlineDev/ReMafoX#21]
## Steps to Reproduce:

1. Experienced "empty key error" documented here (https://github.com/FlineDev/ReMafoX/issues/20)
2. In order to fix empty key, I navigated to the Storyboard in Xcode, and added "#bc-ignore!" to the localizer hint field for that string, as I have for dozens of other strings in my app.
3. Ran "Xcode -> build" to run ReMafoX build script
4. Returned to ReMafoX, experienced https://github.com/FlineDev/ReMafoX/issues/20 again for the same key
5. Looked in Xcode, realized that the key was in the storyboard's English .strings file, indicating that ReMafoX did not apply the ignore flag as Bartycrouch would have
6. Tried manually using the "Update Strings files from Storyboard/XIB files" button in ReMafoX, no change.

## Expected Behavior:

In bartycrouch, adding #bc-ignore! to a localizer hint and re-building in Xcode would remove the string in question from the localized .strings files. That's not happening here.

## Environment

<details>
<summary>Show environment details</summary>
- App Version: 1.0.2 (Build 51)
- System Version: 13.0 (Build 22A5373b)
- System CPU: Apple M1

</details>

**Comment by lukemmtt** [comment]
Indeed, the bartycrouch ignore flags are present. I also tried using the "#remafox-ignore" flag, no change.

It's worth noting that these flags are obviously working in some capacity, because the many other storyboard strings for which I had previously added "#bc-ignore!" to are not being erroneously added by the build script—it is just the blank strings that I forgot about that I can't seem to get rid of.

Also worth noting, I have removed the bartycrouch build script and swiftgen build script from my project, but the "Strings.swift" file that was created by swiftgen remains (as I have hundreds of enums in there that my project depends on for now, unless you have some magic tool for automatically changing all my old refs to that file to the new ReMaFoX.swift enum hierarchy of course?)

<img width="706" alt="Screenshot 2022-10-13 at 3 39 55 PM" src="https://user-images.githubusercontent.com/1598289/195693809-7eed5f95-6f05-458d-982b-ef5ec64683ca.png">

**Comment by Jeehut** [comment]
@lukemmtt Thank you for looking that up. As you say that it doesn't seem to happen everywhere and that you had forgotten to add the ignore flag at first, have you tried removing the key manually from the source language `.strings` file and building your project (to run the build script)? I would expect the normalizer then remove the key from all other languages for you and the IB files updater to ignore the key as expected.

If this still continues to happen though, could you please provide me with a Storyboard or XIB file where I can reproduce the issue so I can provide a fix? Feel free to send it to support@fline.dev if you don't want to upload it publicly.

**Comment by lukemmtt** [comment]
> have you tried removing the key manually from the source language .strings file and building your project (to run the build script)? I would expect the normalizer then to remove the key from all other languages for you and the IB files updater to ignore the key as expected and not add it to the source language again.

Yup, tried that. It adds it right back.

Here's a screen recording for you:
https://user-images.githubusercontent.com/1598289/195698964-14c875d6-c98a-47b0-9d08-5d1e3bc4b27d.mp4

And here's the storyboard:
[Onboarding.storyboard.zip](https://github.com/FlineDev/ReMafoX/files/9780312/Onboarding.storyboard.zip)

**Comment by lukemmtt** [comment]
@Jeehut possible correction—I'm not sure the "ignore flags" are working at all, even for things that I flagged before installing ReMafoX. 

Here is a screenshot of an item that has been labeled with bc-ignore for ages:
![Screenshot 2022-10-13 at 4 24 40 PM](https://user-images.githubusercontent.com/1598289/195703670-1ec6ccb6-003a-4141-ab51-be8c98fdec05.png)

**Comment by Jeehut** [comment]
@lukemmtt Thanks for the fast responses. I'll make sure to take a look tomorrow! This shouldn't happen, of course.

**Comment by Jeehut** [comment]
Just uploaded and submitted version `1.0.3` with the fix for review. Should be available in ~24 h from now.
