### ISSUE TITLE
[Feat] Support more languages than the current 40

### ISSUE THREAD

**Issue by Jeehut** [FlineDev/ReMafoX#39]
## Problem Statement

Currently ReMafoX supports only 40 languages, which covers a good part of apps, but some apps just need to support some languages outside of these 40. Especially if they were written in a country outside of these 40 languages the app might need just this one more language to be supported, which is annoying.

## Suggested Solution

Add many more languages, for example all the ones listed in the Xcode dropdown when adding a new language.

## Additional Considerations

See also https://github.com/FlineDev/ReMafoX/issues/31 which requests support for English variants.

**Comment by Sherlouk** [comment]
Linking this to #32 which calls out the Welsh language specifically. Happy to close that if we'd rather keep everything together? Maybe folks can post their preferred missing languages as a comment in this issue and folks can upvote on each language individually without flooding the project with language suggestions?

**Comment by Jeehut** [comment]
@Sherlouk Please see my latest comment in #32. Apart from that, as of now, I don't think it's necessary for me to know which languages are most expected as once I start working on this task, it's more efficient to add a whole bunch of langauges right away and I think I'll manage to add an additional 50-100 in one go, which should then hopefully cover (nearly) all languages supported by Xcode.

After that, I think it would make sense for people to request languages one at a time. But thank you for being active here and trying to help the community. It's much appreciated! Just not needed in this case. 🙂

**Comment by Jeehut** [comment]
This feature was just implemented and will be part of the next feature release `1.2.0`. I managed to bring the supported languages to more than a hundred! 🎉

**Comment by Jeehut** [comment]
FYI: I just submitted version `1.2.0` including this feature to the App Store! Should be online within 24h. 🎉
