### ISSUE TITLE
[Feat] Add support for Yandex translation service

### ISSUE THREAD

**Issue by anivaros** [FlineDev/RemafoX#4]
## Problem Statement

I want to use custom translator ([Yandex.Translate](https://cloud.yandex.com/en-ru/docs/translate/))

## Suggested Solution

It wold be nice to be able connect custom translation engines by specifying api requests for them.

**Comment by Jeehut** [comment]
@anivaros Thank you for posting the first feature request! (Of course, you also posted the first official bug report. 👏 )

Adding more translation services is definitely something I'd like to do with the monthly future updates planned. I didn't have Yandex on my list yet, so thank you for mentioning it. To everyone interested the Yandex translation service, please upvote (👍) this feature request so I can prioritize accordingly.

For future reference, here's the translate endpoint REST API documentation to be implemented (+ quote limit logic):
https://cloud.yandex.com/en-ru/docs/translate/api-ref/Translation/translate

**Comment by Jeehut** [comment]
@anivaros Please note that I did recognize that you were asking for a way to add support for any translation service yourself. But it's not that easy to provide a generalized way of allowing users to add their custom services, I think this is much more complicated than me implementing each service myself – there's only so much translation services available anwyays.

Each service has a different method for authorization, a different way of communicating rate limits, and a different method for checking for usage limits for a specific user. I don't think there's a way to provide an extension point with a good user experience, thus I will try to add and support as many translation services as possible. I hope this is fine with you, too.

**Comment by Jeehut** [comment]
@anivaros, @noxt: I just uploaded a new version (`1.4.0`) including this feature to App Store Connect. The update should be available within 24 hours. Thanks for suggesting & voting on this feature and helping me prioritize!
