### ISSUE TITLE
[Bug] Help Menu Text misaligned

### ISSUE THREAD

**Issue by gaige** [FlineDev/ReMafoX#46]
## Steps to Reproduce:

1. Launch application
2. Pull down Help menu

## Expected Behavior:

Menu item titles should line up vertically

## Current Behavior:

It appears that the symbols on the left of the items are not exactly the same width. It's mostly aligned, but there are cases where they're off by a pixel or two.  I'm not sure how you're generating the menus, but assuming these are SFSymbols, you may be able to use the SFMono variant.
![CleanShot 2022-10-16 at 04 53 59@2x](https://user-images.githubusercontent.com/3351751/196027526-0f1622fa-a82e-4333-898b-c1347da3c431.png)

## Environment

<details>
<summary>Show environment details</summary>

- App Version: 1.0.2 (Build 51)
- System Version: 12.6 (Build 21G115)
- System CPU: Intel(R) Xeon(R) W-3245 CPU @ 3.20GHz

</details>

**Comment by Jeehut** [comment]
@gaige Thank you for reporting this.

The fix was obvious, so I already fixed it. It'll be available in `1.0.4`. 🎉 😄

**Comment by Jeehut** [comment]
I just submitted version `1.0.4` for App Review, the update with the fix for this should be available within 24 hours. 🎉
