### ISSUE TITLE
[Bug] Slow typing performance in path window

### ISSUE THREAD

**Issue by gaige** [FlineDev/ReMafoX#47]
## Steps to Reproduce:

1. Create a ReMafoX project with an Xcode project that contains a large number (38,000) files
2. Go to the *Search Paths* window
3. Type in any of the paths boxes

## Expected Behavior:

Typing should be responsive

## Current Behavior:

Typing can become sluggish (on 16-core 2019 MacPro with macOS 12.6)

(Attached video should show this, and you should be able to see this with the project I sent yesterday)
https://user-images.githubusercontent.com/3351751/196028002-7a410575-2dce-4c75-b9f1-ea36afb46e2a.mp4

## Environment

<details>
<summary>Show environment details</summary>

- App Version: 1.0.2 (Build 51)
- System Version: 12.6 (Build 21G115)
- System CPU: Intel(R) Xeon(R) W-3245 CPU @ 3.20GHz

</details>

**Comment by Jeehut** [comment]
@gaige Thank you for reporting this.

Will test more with large projects to fix this, shouldn't hang of course!

**Comment by Sherlouk** [comment]
For what it's worth, this was the exact same experience as mentioned in #37. I wasn't seeing it on Monterey though, only Ventura. Small project.

**Comment by Jeehut** [comment]
@gaige @Sherlouk I fixed this issue and the fix will be part of the new release `1.1.0` which I just submitted to the App Store. It should be available within ~24 hours. If you run into this issue again, please let me know.
