### ISSUE TITLE
[Bug] Command Key for Project Window

### ISSUE THREAD

**Issue by gaige** [FlineDev/ReMafoX#48]
## Steps to Reproduce:

1. Start ReMafoX
2. Click in Windows menu

## Expected Behavior:

Some (although not even all Apple-made) apps that have main windows use CMD-0 to bring these up.  For example, Mail.app. 
That's not absolutely required, but as mentioned below, unexpected to see CMD-P as a window command key instead of print is unexpected.

## Current Behavior:

CMD-P is reserved for Print on macOS, recommend avoiding that for window selection.

## Environment

<details>
<summary>Show environment details</summary>

- App Version: 1.0.2 (Build 51)
- System Version: 12.6 (Build 21G115)
- System CPU: Intel(R) Xeon(R) W-3245 CPU @ 3.20GHz

</details>

**Comment by Jeehut** [comment]
@gaige That's a good point. Wasn't aware that there's already a go-to command for it. Clearly one of the things I have to learn about Mac App development as someone with an iOS developer background.

I implemented the change already, will be available with the next update `1.0.4`.
