### ISSUE TITLE
[Bug] Swift file includes Xcode managed strings

### ISSUE THREAD

**Issue by Sherlouk** [FlineDev/ReMafoX#49]
## Steps to Reproduce:

[ as requested on Twitter ]

1. Add an .intentdefinition file to your project
1. Localise it
1. See how the random identifiers generated by Xcode are added to the ReMafoX.swift file

## Expected Behavior:

Randomly generated identifiers generated by Xcode should not really be in the Swift generated file. These aren't intended to be used at runtime by our own source code and as such we don't need type-safe access to them. Xcode handles all of that.

I'm raising this issue for `intentdefinition` specifically, but is also true for any file aside from strings(dict). This includes (but is not strictly limited to) setting bundles, sprite kit files, and more. ReMafoX already supports this for XIBs/storyboards.

## Current Behavior:

Intents strings are generated into Swift, but are unnecessary and unused.

## Environment

<details>
<summary>Show environment details</summary>

- App Version: 1.0.3 (Build 52)
- System Version: 13.0 (Build 22A5342f)
- System CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
- Tier: Max (yeahhh boiiiii, cash moneyyyy)

</details>

**Comment by Jeehut** [comment]
Thank you for reporting this.

It makes a lot of sense to ignore all files that are Base-localized, including Intent definition files. I'll make sure to adjust the logic to be more permissive of other kinds of files than just Storybord and XIB files, which are already excluded from the Swift file at the moment.

**Comment by Jeehut** [comment]
I just improved the way I exclude Base-localized Strings files from the generated code, which should fix this issue.

The fix will be included as part of the next update `1.1.1` to be released soon. I'll keep you updated!

**Comment by Jeehut** [comment]
I just submitted version `1.1.1` with the fix to the App Store. It should be available within 24 hours. 🎉
