### ISSUE TITLE
[Bug] [Code: PRAxMMMC] Machine translation authorization error

### ISSUE THREAD

**Issue by nickfedoroff** [FlineDev/ReMafoX#51]
## Steps to Reproduce:

1. On Machine Translation tab, add Microsoft Translator API Key in Setup API Keys
1. On Machine Translation Tab, click "Start Batch Translation"

## Expected Behavior:

Machine translation completes without error.

## Current Behavior:

Error popup appears with message about 401 error from translation service. See screenshot.

<img width="1552" alt="Screen Shot 2022-10-16 at 10 58 34 PM" src="https://user-images.githubusercontent.com/1442451/196100176-320a3a94-f2f6-42d0-a8b7-ec7ed7a3d346.png">

## Environment

PRAxMMMC

<details>
<summary>Show environment details</summary>

- App Version: 1.0.3 (Build 52)
- System Version: 12.6 (Build 21G115)
- System CPU: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
- Tier: Pro

</details>

**Comment by LiviuJianu** [comment]
A dropdown for selecting the region on where Microsoft Translation is deployed needs to be added. 
When sending the same request using an HTTP Client, but adding the header parameter: `Ocp-Apim-Subscription-Region: eastus` it works.

**Comment by Jeehut** [comment]
@nickfedoroff Thank you for reporting this and thank you @LiviuJianu for providing additional context.

I will make sure to check this quickly and push an update with a fix (e.g. options for choosing the region as suggested).

**Comment by Jeehut** [comment]
@nickfedoroff @LiviuJianu
I just implemented a text field for providing a region, it will be released very soon as part of version `1.0.4`.

Please note that I opted against providing a dropdown with a limited list, even though this might seem convenient. The reason for that is that neither could I find any documentation of the full list of available regions anywhere in the related [Azure API documentation](https://learn.microsoft.com/en-us/azure/cognitive-services/translator/reference/v3-0-reference), nor do I see any reason why users should need to wait for me to push an update of the app with an updated list of regions even if I figured the full list out myself. Unlike the list of supported language per service, there's no need to do any kind of mapping so I felt providing a text field is not only the easiest but also the best option here.

**Comment by Jeehut** [comment]
I just submitted version `1.0.4` for App Review, the update with the fix for this should be available within 24 hours. 🎉
