### ISSUE TITLE
[Bug] [Code: PBRxCRX] Not able to open ReMaFox projects

### ISSUE THREAD

**Issue by Sn0wfreezeDev** [FlineDev/ReMafoX#54]
## Steps to Reproduce:

1. Open a recent ReMaFox project
1. The App fails and tells me that the <Project>.remafox file does not exist 
1. Re-opening the project from the existing project file leads to the same error 
2. Deleting the project and re-opening it leads to the same error

## Expected Behavior:

I'd expect that the project can be opened in ReMaFox

## Current Behavior:

I get an error that the Project does not exist

## Environment

See Error code: PBRxCRX

- App Version: 1.0.4 (Build 53)
- System Version: 13.0 (Build 22A379)
- System CPU: Apple M1 Pro
- Tier: Pro

</details>

**Comment by Sn0wfreezeDev** [comment]
I re-created the project and it works again. Might be an issue related to that I created this project while ReMaFox was still in beta.

**Comment by Jeehut** [comment]
@Sn0wfreezeDev Yes, the error code `PBRxCRX` is clearly an indicator that your config file did not have a valid format. And that can only happen if you created the project in an early Beta version but did not install a later Beta-version that contained an automatic migration (see release notes [here](https://remafox.app/changelog/#deprecated-1)). I removed all Beta-migrations in the final release to get rid of some Optionals that seem to have led to this error.

I'm sorry for the inconvenience and I want to confirm that what you did (deleting the project and setting it up again) is the correct workaround here. Such a breaking change will not happen now after the final release, I promise (until I make a v2.0 release at some point, but then with an easy-to-find migration guide).

I'm closing this as it's clearly Beta-related and no longer an issue in the final release.
