### ISSUE TITLE
[Bug] Strings Top-Level Alias Name Change Ignored

### ISSUE THREAD

**Issue by loganisitt** [FlineDev/RemafoX#64]
## Steps to Reproduce:

I changed Strings Top-Level Alias Name from the default "Loc" to "Localized." However, when I "Insert as string" from Add Translation, the code generated continues to use "Loc".

1. Navigate to Generated Code
1. Change Strings Top-Level Alias Name to "Localized" 

## Expected Behavior:

Code generation uses "Localized" or another user-entered name.

## Current Behavior:

Code generation uses "Loc"

## Environment

<details>
<summary>Show environment details</summary>

- App Version: 1.1.1 (Build 55)
- System Version: 13.0.1 (Build 22A400)
- System CPU: Apple M1 Max
- Tier: Pro

</details>

**Comment by Jeehut** [comment]
@loganisitt Thank you for reporting this detailed bug report.

This sounds like an overlook by me in the Xcode source editor extension. I could reproduce this issue and will make sure to fix it with the next update. I'll inform you here once it's fixed.

**Comment by Jeehut** [comment]
@loganisitt I have good news: I just fixed this issue and will be preparing a new release with the fix today!
Expect this to be fixed in the update `1.2.0` to be available within the next few days.

Thank you again for reporting!

**Comment by Jeehut** [comment]
FYI: I just submitted version `1.2.0` with a fix for this to the App Store! Should be online within 24h. 🎉

**Comment by loganisitt** [comment]
Thanks for the update! 

By the way, I've been using BartyCrouch for years, and I love the direction you've gone in with RemafoX. This new tool is fantastic!

**Comment by Jeehut** [comment]
@loganisitt Thanks, that's encouraging to hear!
