### ISSUE TITLE
[Bug] In Dark Mode - The "Copy Code" button has a blank label in Set up Build Script 

### ISSUE THREAD

**Issue by marcrespass** [FlineDev/ReMafoX#68]
## Steps to Reproduce:

1. Step 3 of Set up Build Script has a white Copy Code button but the label is missing in Dark Mode.

## Expected Behavior:

I expected to be able to read the button's label: 

## Environment

<details>
<summary>Show environment details</summary>

- App Version: 1.2.0 (Build 56)
- System Version: 13.0.1 (Build 22A400)
- System CPU: Apple M2
- Tier: Free

</details>

**Comment by Jeehut** [comment]
@marcrespass Thank you for reporting this issue!

This should be easy to fix, I'll make a release soon with it included. Of course, the text should be readable in dark mode, which is very common among developers.

**Comment by Jeehut** [comment]
@marcrespass I just fixed this issue and the fix will be shipped as part of the next `1.2.1` update soon.
Thanks again for reporting! Much appreciated. 💯

**Comment by Jeehut** [comment]
Version `1.2.1` was just submitted to the App Store and should be available within 24 hours.
