### ISSUE TITLE
[Bug] Text input broken - keeps moving cursor to end

### ISSUE THREAD

**Issue by ConfusedVorlon** [FlineDev/ReMafoX#80]
## Steps to Reproduce:

Create a new package - try to edit the generated code location

1. tap on 'Generated Code'
1. tap in 'Resources Swift File Path' field
1. try to edit the field (adding a path to the beginning)

## Expected Behavior:

editing works as normal

## Current Behavior:

after each character, the cursor moves to the end.
presumably, you're observing the value for the field in your parent view - so re-drawing the field every time there is a change

## Environment

<details>
<summary>Show environment details</summary>

- App Version: 1.4.1 (Build 63)
- System Version: 13.2.1 (Build 22D68)
- System CPU: Apple M1 Ultra
- Tier: Free
</details>

**Comment by Jeehut** [comment]
@ConfusedVorlon Thank you for reporting this issue.

You guessed right, I have a parent-view redrawing problem here. I'm in the middle of moving cities, so I won't have time to fix this bug this week, but I will make sure to tackle it as soon as possible (probably next week).

As a workaround until then, you can simply write the whole String you want to add to the beginning (or middle) of the field in another app (e.g. Spotlight), then copy it and paste it to RemafoX at the desired location.

**Comment by Jeehut** [comment]
@ConfusedVorlon I just fixed this, it should be shipped as part of `1.5.0` in a couple of days. Thanks for reporting! 🚀
